<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32428" started-at="2021-05-14T16:49:45 IST" finished-at="2021-05-14T16:50:18 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32428" started-at="2021-05-14T16:49:45 IST" finished-at="2021-05-14T16:50:18 IST">
      <class name="com.testcases.LoginPageTest">
        <test-method status="FAIL" signature="doLoginTest(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.LoginPageTest@587d1d39]" name="doLoginTest" duration-ms="8354" started-at="2021-05-14T16:49:46 IST" data-provider="getLoginData" finished-at="2021-05-14T16:49:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[validemail@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[validpassword]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login is not successfull expected [HRS | ClinicianConnect | loggedin] but found [HRS | ClinicianConnect]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login is not successfull expected [HRS | ClinicianConnect | loggedin] but found [HRS | ClinicianConnect]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.hrs.pages.LoginPage.assertLoggedInOrNot(LoginPage.java:70)
at com.testcases.LoginPageTest.doLoginTest(LoginPageTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
        <test-method status="PASS" signature="takeScreenShotOnFfailure(org.testng.ITestResult)[pri:0, instance:com.testcases.LoginPageTest@587d1d39]" name="takeScreenShotOnFfailure" is-config="true" duration-ms="264" started-at="2021-05-14T16:49:54 IST" finished-at="2021-05-14T16:49:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=doLoginTest status=FAILURE method=LoginPageTest.doLoginTest(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.LoginPageTest@587d1d39] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFfailure -->
        <test-method status="FAIL" signature="doLoginTest(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.LoginPageTest@587d1d39]" name="doLoginTest" duration-ms="5757" started-at="2021-05-14T16:49:54 IST" data-provider="getLoginData" finished-at="2021-05-14T16:50:00 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[validemail@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[invalidpassword]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login is not successfull expected [HRS | ClinicianConnect | loggedin] but found [HRS | ClinicianConnect]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login is not successfull expected [HRS | ClinicianConnect | loggedin] but found [HRS | ClinicianConnect]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.hrs.pages.LoginPage.assertLoggedInOrNot(LoginPage.java:70)
at com.testcases.LoginPageTest.doLoginTest(LoginPageTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
        <test-method status="PASS" signature="takeScreenShotOnFfailure(org.testng.ITestResult)[pri:0, instance:com.testcases.LoginPageTest@587d1d39]" name="takeScreenShotOnFfailure" is-config="true" duration-ms="608" started-at="2021-05-14T16:50:00 IST" finished-at="2021-05-14T16:50:01 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=doLoginTest status=FAILURE method=LoginPageTest.doLoginTest(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.LoginPageTest@587d1d39] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFfailure -->
        <test-method status="FAIL" signature="doLoginTest(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.LoginPageTest@587d1d39]" name="doLoginTest" duration-ms="5904" started-at="2021-05-14T16:50:01 IST" data-provider="getLoginData" finished-at="2021-05-14T16:50:07 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[invalidemail@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[validpassword]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login is not successfull expected [HRS | ClinicianConnect | loggedin] but found [HRS | ClinicianConnect]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login is not successfull expected [HRS | ClinicianConnect | loggedin] but found [HRS | ClinicianConnect]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.hrs.pages.LoginPage.assertLoggedInOrNot(LoginPage.java:70)
at com.testcases.LoginPageTest.doLoginTest(LoginPageTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
        <test-method status="PASS" signature="takeScreenShotOnFfailure(org.testng.ITestResult)[pri:0, instance:com.testcases.LoginPageTest@587d1d39]" name="takeScreenShotOnFfailure" is-config="true" duration-ms="590" started-at="2021-05-14T16:50:07 IST" finished-at="2021-05-14T16:50:07 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=doLoginTest status=FAILURE method=LoginPageTest.doLoginTest(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.LoginPageTest@587d1d39] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFfailure -->
        <test-method status="FAIL" signature="doLoginTest(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.LoginPageTest@587d1d39]" name="doLoginTest" duration-ms="5854" started-at="2021-05-14T16:50:07 IST" data-provider="getLoginData" finished-at="2021-05-14T16:50:13 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[invalidemail@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[invalidpassword]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login is not successfull expected [HRS | ClinicianConnect | loggedin] but found [HRS | ClinicianConnect]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login is not successfull expected [HRS | ClinicianConnect | loggedin] but found [HRS | ClinicianConnect]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.hrs.pages.LoginPage.assertLoggedInOrNot(LoginPage.java:70)
at com.testcases.LoginPageTest.doLoginTest(LoginPageTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
        <test-method status="PASS" signature="takeScreenShotOnFfailure(org.testng.ITestResult)[pri:0, instance:com.testcases.LoginPageTest@587d1d39]" name="takeScreenShotOnFfailure" is-config="true" duration-ms="612" started-at="2021-05-14T16:50:13 IST" finished-at="2021-05-14T16:50:14 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=doLoginTest status=FAILURE method=LoginPageTest.doLoginTest(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.LoginPageTest@587d1d39] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFfailure -->
        <test-method status="PASS" signature="closeLoginPage()[pri:0, instance:com.testcases.LoginPageTest@587d1d39]" name="closeLoginPage" is-config="true" duration-ms="4146" started-at="2021-05-14T16:50:14 IST" finished-at="2021-05-14T16:50:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeLoginPage -->
      </class> <!-- com.testcases.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
